version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "loginTestDemoSallee"
s3_bucket = "login-test-demo-sallee"
s3_prefix = "loginTestDemoSallee"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
