AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    product 2 , refactor and faster interaction wilth villa master product
    
Globals:
  Function:
    Timeout: 10
    CodeUri: ./app
    Runtime: python3.8
    Layers:
      - !Ref LambdaLayer
    Environment:
      Variables:
        USERDATATABLE: !Join ['-', ['user', 'data', 'demo1', !Ref BRANCH]]
        USERPASSWORDTABLE: !Join ['-', ['user', 'password', 'demo1', !Ref BRANCH]]
      
      
Parameters: 
  BRANCH: 
    Type: String
    Default: dev-manual
    Description: root branch name
  REGION:
    Type: String
    Default: 'ap-southeast-1'
    
    
Resources:
  ######## api gateway #######
  Endpoint:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        
  ######## functions ######
  SignIn:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ['-',[ "sign-in-login-demo1",!Ref BRANCH ]]
      Handler: app.signIn
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserPasswordTable
      Events:
        GetProduct:
          Type: Api 
          Properties:
            Path: /signIn
            Method: get
            RestApiId: !Ref Endpoint
            
  SignUp:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ['-',[ "sign-up-login-demo1",!Ref BRANCH ]]
      Handler: app.signUp
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserPasswordTable
      Events:
        GetProduct:
          Type: Api 
          Properties:
            Path: /signup
            Method: post
            RestApiId: !Ref Endpoint
            
  ###### dynamodb ########
  UserDataTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: username
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
#       GlobalSecondaryIndexes:
#         - IndexName: phoneNumber
#           KeySchema:
#             - AttributeName: phoneNumber
#               KeyType: HASH
#           Projection:
#             ProjectionType: ALL
      KeySchema: 
        - AttributeName: username
          KeyType: HASH
      TableName: !Join ['-', ['user', 'data', 'demo1', !Ref BRANCH]]
      
  #### simpleTable #####
  UserPasswordTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: username
        Type: String
      TableName: !Join ['-', ['user', 'password', 'demo1', !Ref BRANCH]]
            

###### lambdaLayer ######

  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lambdalayer
      ContentUri: ./layer/package.zip
      CompatibleRuntimes:
        - python3.8

  LayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LambdaLayer
      Principal: "*"



Outputs:
  ApiId:
    Value: !Ref Endpoint
  Endpoint:
    Value: !Sub 'https://${Endpoint}.execute-api.${REGION}.amazonaws.com/Prod/'
