AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    product 2 , refactor and faster interaction wilth villa master product
    
Globals:
  Function:
    Timeout: 10
    CodeUri: ./app
    Runtime: python3.8
    Layers:
      - !Ref LambdaLayer
    Environment:
      Variables:
        USERNUMBERTABLE: !Join ['-', ['user', 'number', 'table','sallee', !Ref BRANCH]]
        USERPASSWORDTABLE: !Join ['-', ['user', 'password', 'demo', 'sallee', !Ref BRANCH]]
      
      
Parameters: 
  BRANCH: 
    Type: String
    Default: dev-manual
    Description: root branch name
  REGION:
    Type: String
    Default: 'ap-southeast-1'
    
    
Resources:
  ######## api gateway #######
  Endpoint:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        
  ######## functions ######
  SignInDemoSallee:
    Type: AWS::Serverless::Function 
    Properties:
      Policies:
        DynamoDBReadPolicy:
          TableName: !Join ['-', ['user', 'number', 'table','sallee', !Ref BRANCH]]
      FunctionName: !Join ['-',[ "sign-in-login-demo-sallee",!Ref BRANCH ]]
      Handler: app.signIn
      Events:
        GetProduct:
          Type: Api 
          Properties:
            Path: /signIn
            Method: post
            RestApiId: !Ref Endpoint
            
  SignUpDemoSallee:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ['-',[ "sign-up-login-demo-sallee",!Ref BRANCH ]]
      Handler: app.signUp
      Events:
        GetProduct:
          Type: Api 
          Properties:
            Path: /signUp
            Method: post
            RestApiId: !Ref Endpoint
        
  ChangePasswordDemoSallee:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ['-',[ "change-password-login-demo-sallee",!Ref BRANCH ]]
      Handler: app.changePassword
      Events:
        GetProduct:
          Type: Api 
          Properties:
            Path: /change_password
            Method: post
            RestApiId: !Ref Endpoint

  GenerateRandomNumberSallee:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Join ['-',[ "generate-random-number-sallee",!Ref BRANCH ]]
      Handler: app.generateRandomNumber
      Events:
        GetProduct:
          Type: Api 
          Properties:
            Path: /generateRandomNumber
            Method: post
            RestApiId: !Ref Endpoint

####### table #########
  PasswordTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: username
        Type: String
      TableName: !Join ['-', ['user', 'password', 'demo', 'sallee', !Ref BRANCH]]
      Tags: 
        SamApp: SamApp
###### lambdaLayer ######

  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lambdalayer
      ContentUri: ./layer/package.zip
      CompatibleRuntimes:
        - python3.8

  LayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LambdaLayer
      Principal: "*"



Outputs:
  ApiId:
    Value: !Ref Endpoint
  Endpoint:
    Value: !Sub 'https://${Endpoint}.execute-api.${REGION}.amazonaws.com/Prod/'
