# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"USERPASSWORDTABLE": "signUp.ipynb",
         "Thread": "signUp.ipynb",
         "logger": "signUp.ipynb",
         "HelperError": "signUp.ipynb",
         "ParseInputError": "signUp.ipynb",
         "CheckDatabaseError": "signIn.ipynb",
         "QueryDatabaseError": "signIn.ipynb",
         "GetAttributeError": "signIn.ipynb",
         "NewPasswordError": "changePassword.ipynb",
         "H": "signUp.ipynb",
         "EventInput": "signUp.ipynb",
         "changePassword": "changePassword.ipynb",
         "signIn": "signIn.ipynb",
         "AddUserError": "signUp.ipynb",
         "CreateTableError": "signUp.ipynb",
         "UsernameAvailabilityError": "signUp.ipynb",
         "signUp": "signUp.ipynb"}

modules = ["Thread.py",
           "changePassword.py",
           "signIn.py",
           "signUp.py"]

doc_url = "https://thanakijwanavit.github.io/src/"

git_url = "https://github.com/thanakijwanavit/src/tree/main/"

def custom_doc_links(name): return None
