# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/get.ipynb (unless otherwise specified).

__all__ = ['get']

# Cell
from awsSchema.apigateway import Response, Event
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, JSONAttribute, NumberAttribute
from copy import deepcopy

# Cell
from .table import SimpleTable
from .getEnv import BUCKETNAME

# Cell

# input is querying an object id {id: OBJECT_ID}
def get(event, *args):
  id_ = Event.parseQuery(deepcopy(event))['id']
  r  = [item.toDict() for item in SimpleTable.query(id_)]
  return Response.returnSuccess(body = {'objects': r})