# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/get.ipynb (unless otherwise specified).

__all__ = ['get']

# Cell
from awsSchema.apigateway import Response, Event

# Cell
def get(event, *args):
  return Response.returnSuccess(body = {'thisisthegetfunction': 'hellooo'})