# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/env/getEnv.ipynb (unless otherwise specified).

__all__ = ['USERDATATABLE', 'USERPASSWORDTABLE']

# Cell
import os
USERDATATABLE = os.environ.get('USERDATATABLE')
USERPASSWORDTABLE = os.environ.get('USERPASSWORDTABLE')