# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/NumberTable.ipynb (unless otherwise specified).

__all__ = ['USERNUMBERTABLE', 'NumberTable']

# Cell
import os
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, NumberAttribute

# Cell
################ Setting Globals from Env Vars ################
USERNUMBERTABLE = os.environ['USERNUMBERTABLE']

# Cell
############## Class for accessing DynamoDB #################
class NumberTable(Model):
    class Meta:
        table_name = USERNUMBERTABLE
        region = 'ap-southeast-1'

    username = UnicodeAttribute(hash_key=True, attr_name='username')
    number = NumberAttribute(attr_name='number')
