# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/passwordTable.ipynb (unless otherwise specified).

__all__ = ['UserPasswordTable']

# Cell
from .getEnv import USERPASSWORDTABLE

# Cell
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute

# Cell
class UserPasswordTable(Model):
  class Meta:
    table_name = USERPASSWORDTABLE
    region = 'ap-southeast-1'
  username = UnicodeAttribute(hash_key=True)
  passwordHash = UnicodeAttribute()

  def __repr__(self): return f'{self.username} - {self.passwordHash}'
