# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/passwordHelper.ipynb (unless otherwise specified).

__all__ = ['hashPassword', 'checkPassword']

# Cell
import uuid
import hashlib

def hashPassword(password):
    # uuid is used to generate a random number
    salt = uuid.uuid4().hex
    return hashlib.sha256(salt.encode() + password.encode()).hexdigest() + ':' + salt

def checkPassword(hashed_password, user_password):
    password, salt = hashed_password.split(':')
    return password == hashlib.sha256(salt.encode() + user_password.encode()).hexdigest()