# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/setEnv.ipynb (unless otherwise specified).

__all__ = []

# Cell
import os
os.environ['BUCKETNAME'] = 'testbucket2-check-master'
os.environ['TABLENAME'] = 'testtable1-check-master'
os.environ['SIMPLETABLENAME'] = 'testsimpletable1-check-master'
os.environ['AWS_PROFILE'] = 'tenxor'