# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/env/setEnv.ipynb (unless otherwise specified).

__all__ = []

# Cell
import os
os.environ['USERDATATABLE'] = 'user-data-demo-master'
os.environ['USERPASSWORDTABLE'] = 'user-password-demo-master'