# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/signIn.ipynb (unless otherwise specified).

__all__ = ['signIn']

# Cell
from awsSchema.apigateway import Event,Response

# Cell
def signIn(event, *args):

  return Response.returnSuccess("this is sign in function")

# Cell
# from beartype import beartype
# from awsSchema.apigateway import Response, Event
# from dataclasses import dataclass
# from dataclasses_json import dataclass_json
# from copy import deepcopy

# Cell
# from src import passwordHelper as PH
# from src.passwordTable import UserPasswordTable

# Cell
# def signIn(event, *args):
#   user = H.parseInput(event)
#   if not H.checkPassword(user):
#     return Response.returnError('user or password is wrong')
#   return Response.returnSuccess({'token': H.makeJWT()})


