# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/signUp.ipynb (unless otherwise specified).

__all__ = ['User', 'H', 'signUp']

# Cell
from beartype import beartype
from awsSchema.apigateway import Response, Event
from dataclasses import dataclass
from dataclasses_json import dataclass_json
from copy import deepcopy

# Cell
from src import passwordHelper as PH
from .passwordTable import UserPasswordTable

# Cell
@dataclass_json
@dataclass
class User:
  username:str
  password:str

  @property
  def passwordHash(self):
    return PH.hashPassword(self.password)

  def save(self):
    table = UserPasswordTable(
      username = self.username,
      passwordHash = self.passwordHash
    )
    table.save()


# Cell
class H:
  class ParseInputError(Exception): pass
  class SavingUserError(Exception): pass
  @classmethod
  @beartype
  def parseInput(cls,event:dict)->User:
    try:
      user = Event.parseDataClass(User,deepcopy(event))
      return user
    except Exception as e:
      raise cls.ParseInputError(e)

  @classmethod
  @beartype
  def save(cls, user:User)->bool:
    try:
      user.save()
      return True
    except Exception as e:
      raise cls.SavingUserError(e)




# Cell
def signUp(event, *args):
  try:
    user = H.parseInput(event)
    H.save(user)
    return Response.returnSuccess()
  except H.SavingUserError as e:
    return Response.returnError(f'failed saving user {e}')
  except Exception as e:
    return Response.returnError(f'unknown error {e}')