# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/table.ipynb (unless otherwise specified).

__all__ = ['SimpleTable']

# Cell
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, JSONAttribute, NumberAttribute
from .getEnv import SIMPLETABLENAME

# Cell
class SimpleTable(Model):
  class Meta:
      table_name = SIMPLETABLENAME
      region = 'ap-southeast-1'
  id = UnicodeAttribute(hash_key=True)
  data = JSONAttribute()
  date = NumberAttribute()


  def toDict(self):
    return {
      'id' : self.id,
      'data' : self.data,
      'date' : self.date
    }

  @classmethod
  def fromDict(cls, dict_):
    return cls(
      id = dict_['id'],
      data = dict_['data'],
      date = dict_['date']
    )

  def __repr__(self): return f'{self.id}\n{self.data}\n{self.date}'