# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/Thread.ipynb (unless otherwise specified).

__all__ = ['USERPASSWORDTABLE', 'Thread']

# Cell
import os
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute

# Cell
################ Setting Globals from Env Vars ################
USERPASSWORDTABLE = os.environ['USERPASSWORDTABLE']

# Cell
############## Class for accessing DynamoDB #################
class Thread(Model):
    class Meta:
        table_name = USERPASSWORDTABLE
        region = 'ap-southeast-1'

    username = UnicodeAttribute(hash_key=True, attr_name='username')
    passwordHash = UnicodeAttribute(attr_name='passwordHash')
    salt = UnicodeAttribute(attr_name='salt')
    hashAndSalt = UnicodeAttribute(attr_name='hashAndSalt')

